# READ FILE EXAMPLE START

#Today Class Target
How can we file and file manipulation,Libraries ko kaisa import krta ha
Also we covered Numpy 
Numpy ka matlab means mukti dimensions array so array ka darmian ap samishan
krata ha is normally done throug python programming ap loop lagana prta ha 
jis ka behalf pr wo proper kam krta but in numpy it can work in proper way
numerical computing hogae,apka ps koi algebric ka behalf ma ap jb matrices 
ki koi implementation krta ho for that purpose we used numpy library


In [13]:
#How can we read other file
#on home page                                            New
#                                                        Notebook: 
#                                                         python3
#                                                         Otherfile:
#                                                         Textfie
#                                                          Folder
#                                                          Terminal
#we go on Textfile create text file and save it without save it will not work.
#ab mna jo textfile banae ha is ka data ko ma pthon is page pr read kro
#ab mna  with open("untitled.txt")apni file ka naam ps krdiya
#as  ksi variable ka ander humko ya data chaya
#ab ma is data aik variable ma stored kro ga jis ka naam mna contents rkha ha
#ab mujha is pr read ka fuction perform krwana ha

#open ko jo method hota ha jo apki is file ko open kraga jo ap read krna chata 
#ho 
#then jo apka ps content araha isko specific name dena zarori ha then 
#with ka keyword for example open ka keyword sa ap na file open to krdi
#but close kaisa kra ga to with ka function ya functionality perform krta
#jb ap  ki file ma sa tamam content read hojata ha to with ka keyword 
#automatically close krdega file ko



with open("untitled.txt") as practicefile:
    contents= practicefile.read()
    print(contents)

000
111
222


In [14]:
#mna text file ma extra white space de ha 
#123
#456
#789
#
#
#
#
#ab ma cha ta wo extra whitte space na print ho to hum apna code rstrip()
# used kra ga
#iski waja extra nahi ae gi
with open("untitled.txt") as practicefile:
    contents= practicefile.read()
    print(contents.rstrip())

000
111
222


In [4]:
#ab chata hon aik folder bnao is folder sa mera data get ho 
#How can we read other folder file
#on home page                                            New
#                                                        Notebook: 
#                                                         python3
#                                                         Otherfile:
#                                                         Textfie
#                                                          Folder
#                                                          Terminal
#we go on folder create folder
#ab ap nicha dekha ga untitled folder ab is pr click kra ga to ap ko ya
#options mila ga 
#                                                             New
#                                                        Notebook: 
#                                                         python3
#                                                         Otherfile:
#                                                         Textfie
#                                                          Folder
#                                                          Terminal
#ap text file pr click krka aik textfile bnalaga
#and save it without save it will not work.
#mera ps untitled ka naam sa aik file moujood ap ma isko naam
#doga untitled2

#mujha yha apna folder ka naam dena hoga iska baad folder jo file ha is ka naam
#dena hoga bqi syntax waisa hi rha ga jo textfile ka lya used kiya ha

with open("Untitled Folder/untitled2.txt") as practicefile:
    contents= practicefile.read()
    print(contents.rstrip())


umair
ali
osama
uzair
raza
riaza


In [5]:
#abhi tq hum with open() ka ander file ps kr rha tha ab hum aik variable bna kr 
#is ka file ps kra ga
#mna file path ka variable bnalya ha ab hum is ka ander aik dafa file location
#dalda ga is ka baad dobra dalna ki hum ko zarorat nhi
filepath = "Untitled Folder/untitled2.txt"
#is ka baad with open ap just file ps kra ga is ma location ko br br dena ki
# zarorat nhi hogi
with open(filepath) as practicefile:
    contents= practicefile.read()
    print(contents.rstrip())


umair
ali
osama
uzair
raza
riaza


In [15]:
#agr ma chata hon for ka loop chalaao with ka method to ma asa kya karo ka 
#tamam cheeza mujha for ka loop ma mil jaa with ka ander ki
#filepath = "untitled.txt"
#with open(filepath) as practicefile:
 #   contents= practicefile.read()
    
#ab ma chata ho yha print na ho balqa outside of the scoope print ho
#mera with scope and(khatam) ho chuka ha ab ma chata hon
#ab is scope sa bhr cheezon ko get kro to wo ma kaisa kro ga
#hum na loop ka ander forin ka loop pra tha ya kb kam ata ha jb text file
#ka ander multiple line ho ,jb multiple aka ps content ho to ap isko loop
#chalaka one by one kaisa get kra
#ab hum srf read konhi balqa readlines ka method ko used kra ga
filepath = "untitled.txt"
with open(filepath) as practicefile:
    contents= practicefile.readlines()

    
for line in contents:
    print(line)



000

111

222


In [16]:
#for removing empty spaces we rstrip()
filepath = "untitled.txt"
with open(filepath) as practicefile:
    contents= practicefile.readlines()

    
for line in contents:
    print(line.rstrip())


000
111
222


In [8]:
#ab ma chta ho mera jitna data ha wo alag line ma print hona ka bjaa aik single
#line ma print hojaa to 

In [17]:
filepath = "untitled.txt"
with open(filepath) as practicefile:
    contents= practicefile.readlines()
#first we declare empty variable
oneline=""

for line in contents:
    oneline += line.rstrip()   #ab hum .rstrip used kra ga jis answer aik
    # line ma print hojaa ga or agr hum rstrip ka method ko call nhi krta to
    #wo empty space ko neglect nhi kra ga
    #oneline += line means oneline aik line pr print kra .
#+= apna jo cheez pass ki ha wo iska ander hi append(add)krta rha ga    
#one file ma line sa value mila gi wo brbr add hota rha gi isma or jakr
#phir oneline"" stored hojaa gi. 

print(oneline)
    
    
    
    
    
    
    
    

000111222


In [18]:
#ab ap chta ha ka apki file  sab content na ae balqa specific content ae
#for 123456789 ma 123456 show ho is baad koi content show na ho
filepath = "untitled.txt"
with open(filepath) as practicefile:
    contents= practicefile.readlines()
#first we declare empty variable
oneline=""

for line in contents:
    oneline += line.rstrip()
#slicing ka method used kra ga 
#[:]
#[:6]agr hum isma starting ma kuch  nhi likha ga to phela 
#number pr cheez hogi isko lala ga first pr
#like yha one ha is lya one is jga pr rekla ga
print(oneline[:6] +"  "+"still continue")
#ab hum check krta ha slicing krna ka baat iski initial length baqi rhagi
# ya nhi
print(len(oneline))
#to iski len isna 9 hi bataae change nhi hoe
print("\n------------------------ xxxxxx-----------------------\nExamples of file read end\n------------------------ xxxxxx-----------------------")

000111  still continue
9

------------------------ xxxxxx-----------------------
Examples of file read end
------------------------ xxxxxx-----------------------


In [20]:
#ab ma chata ho ka  ma apni file ka ander koi cheez write krwada
#yan koi code likho ya koi line likho jo file ma jaka stored hojaa

filepath = "untitled.txt"

with open(filepath,'w') as practicefile:
    practicefile.write("000")
    
    
#agr apko write ka operation perform krna  ha to ap filepath ka sath "w" likha
#ga jo write ka operation ko bata rhi ha.
     

In [21]:
filepath = "untitled.txt"

with open(filepath,'w') as practicefile:
    practicefile.write("000\n")# \n when use multi-line
   # PracticeFile.write("111") #for multi-line for separation we used \n
    practicefile.write("111\n")

In [22]:
#jb mna write ka operation perform kiya to mera ps prona data remove ho gya
#or new data jo mna write ka zarya diya wo agya ab ma chata hon kuch asa kro
#ka porana data bhi mujha miljaa.
#or ma jo new cheez likhwana chahrha wo print ho
#iska hum aik operation perform krta jisko append ka operation kheta ha
filepath = "untitled.txt"
#agr ma yha write ka operaion perform krta hon to content ma overwrite krdaga
#or porana data(content)ko removed krdaga islya hum na 'a'(append) likha jis
#wo is file ma ajaaga or porana data bhi rha ga
with open(filepath,'a') as practicefile:
    practicefile.write("222")
   
    

In [24]:
#suppose we 5 divide 0 agr ya kaam python ko bolo ga to wo dega 0 division
#error to hamara ps python ka ander jo cases hota hainko kheta ha exception
#agr in ko control krna ha jaise ap error pta ha koi bhi cheez 0 sa divide
#to error ae ga 0 division error
#ab hum maaloom python error dedaga to ya cheez humko execution sa phela check
#krani ha
#All programming language ka ander try and catch ko used krta ho 
#try ma koi cheez ko try krta ha 
#or catch ma isma agr koi error hota ha to check krta ha 
#python ka ander hamara ps hota try or exception ka block hota
#koi cheez ap try krta ho suppose in do ko divide krta ho 
#exception ma jo error ae iska against ma apna kya answer dena wo batana hoga
firstnum=5
secondnum=0

try:
    answer=firstnum/secondnum
except ZeroDivisionError:
    print("This operation cannot perform")
else:#agr zero na ho to is else ka block ma answer ko print krdo
    print(answer)

    


This operation cannot perform


In [25]:
firstnum=5
secondnum=3

try:
    answer=firstnum/secondnum
except ZeroDivisionError:
    print("This operation cannot perform")
else:#agr zero na ho to is else ka block ma answer ko print krdo
    print(answer)

    



1.6666666666666667


In [26]:
#some time you find some file python give error that file not found error 
#agr is ko file na mila
try:
    with open("untitled.txt") as practicefile:
        contents= practicefile.read()
        
#agr isko file nhi mile
except FileNotFoundError:
    print("your file path is not correct")
else:#agr file present ho to tamam cheeza contents ma ajaa gi
    print(contents)

000
111
222


In [27]:
#some time you find some file python give error that file not found error 
#agr is ko file na mila
try:
    with open("untitled3.txt") as practicefile:
        contents= practicefile.read()
        
#agr isko file nhi mile
except FileNotFoundError:
    print("your file path is not correct")
else:#agr file present ho to tamam cheeza contents ma ajaa gi
    print(contents)

your file path is not correct


# MODULE EXAMPLE START

In [23]:
#ap ka excel ki file hoti ha wo CSV(Comma Separated Value) file hoti ha
#ab agr ap ka ps koi excel ki file ha isma muliple coloumns hota ha 
#multiple data hota ha in file ka ander ap data kaise get kro ga 
#suppose excel ki file is ma sa ap data kaise get kro ga
#sab sa apna csv ka module import krna 
import csv
with open("Book2.csv") as practicefile:
    contents= csv.reader(practicefile)
    for line in contents:
        print(line)
        #csv.reader is the syntax to excess
#csv file ab for ka loop ki zarorat paragi to excess row and coloumn in excel
#file
 

FileNotFoundError: [Errno 2] No such file or directory: 'Book2.csv'

In [20]:
import csv#EXPORT AS CSV

with open('data.csv') as PracticeFile:
    contents=csv.reader(PracticeFile)
    for line in contents:
        print(line)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [21]:
#BULTIN MODULE HA HAMRA PS HA MATH KA MODULE TO HUM MODULE KO IMPORT KRTA HA
import math#hum ab math ka tamam module ko import krsakta ha
print(math.pi)

3.141592653589793


In [22]:
#ab ma apsa kheta ha ka math ka jo module arha is ka  naam change krdo
import math as mymath#ab ma module apni tamam file mymath ka zarya imort krloga
#ab mujha agr pi ki value chaya ha to mymath ka zarya print krlo ga
print(mymath.pi)

3.141592653589793


In [23]:
#ap ka math ka jo module ha is ma bhot sara operation ha like pi ka ha, square
#ka ha,ceiling,floor,log etc iska multiple operation ha apko pora module import
#nhi krna is ma sa ksi specific fuction ko import krna ha
from math import pi
print(pi)


3.141592653589793


In [25]:
from math import * #star ka matlab ha is module ki tamam cheeza import krlo ga
print(pi)


3.141592653589793


In [26]:
import math #ceiling means next value (or ya value ko round off krka increase 
#krdeta ha)
math.ceil(5.7)

6

In [27]:
import math #floor means previous value(ya round off kr value ko degrade krdeta
#ha yani kam kr deta ha )
math.floor(5.7)

5

In [28]:
#ab mna aik new python ki file banae ha whan mna aik fuction bnaya ha 
#def add(a,b):
 #   result = a+b
  #  return result
#ap is file ka ander function ka result yha hamrae module file ma excess
# kr sakta ha
#ab is tarh ka module hum is tarh import krta ha 
import import_ipynb#ab ma jb import_ipynb likho ga to ma insure krdo ga ka wo 
#wo inma sa ksi file ko import krla

#ab yha sab sa phela apni file ko import kro ga 
import Untitled1
#Untitled1. ka sath jo function perform krna is ko likho ga  
Untitled1.add(5,3)


ModuleNotFoundError: No module named 'import_ipynb'

In [29]:

#ab mna aik new python ki file banae ha whan mna aik fuction bnaya ha 
#def add(a,b):
 #   result = a+b
  #  return result
#ap is file ka ander function ka result yha hamrae module file ma excess
# kr sakta ha
#ab is tarh ka module hum is tarh import krta ha 
import import_ipynb#ab ma jb import_ipynb likho ga to ma insure krdo ga ka wo 
#wo inma sa ksi file ko import krla

#ab yha sab sa phela apni file ko import kro ga 
import Untitled1
#Untitled1. ka sath jo function perform krna is ko likho ga  
Untitled1.add(5,3)
#error is lya aya tha  hum ko ipynb ka jo module ha is install krna zaroori ha 
#ab ma jb isko install kro ga to error gaib hojaa ga
#ab ab home pr gae home pa ana ka baad               new
#                                                    Notebook
#                                                    python3 
#                                                    other
#                                                    TextFile
#                                                    Folder  
#                                                    Terminal
#ab hum terinal p jae ga wha ya (pip install import_ipynb)(ya command is baat 
#ko insure kr rhi ha ka aik file ko dosri file ma excess krsaktaha)
#ya command likho ga #or module install ho jaa ga phir upper wala  
#programrun ho jaa ga


importing Jupyter notebook from Untitled1.ipynb


8

# NUMPY STARTING

#INTRODUCTION:
Numpy apko functionality deta ha multi dimension array bnaa ki
is ka do package or ha 1)Numpy 2)pandas
ya basically fundamental or bhot important package ha apki pyhton programming 
ka kyu ya is cheez ko insure krta apka deta multidimension store krta ha
ap ka apka complex operation jo perform horha hota jis ma apka linear algebra,
computational counting ya tamam ki tamam apka ps jo cheeza perform hoti ha 
bhot huge calculation hoti ha to wha pr ap python ki list or touple wagira
sa kra ga to bhot musqil sa hoga ap isko control nhi krsakta ha 
inko apko controll krna la lya Numpy,pandas in frame work utilize krta ha
apko isko utilize to kr leta ha is baat kya hota ha
ap agr do array ko add krna chta ha to isma ap index add no ko add kra ga
arr1[1,2,3] and arr2[4,5,6] agr ap indono ko add kro ga to for ka loop apply
kro ga python jb ka numpy ma ap by the help of plus(+) sign ap do arrays 
ko add krdeto ho
ap ka brae sa brae array ho muti dimension ho ap iska + sign ki madad sa add 
krsakta ho or linear algebra or complex calculation ma apko functionality 
provide krta ha ka ap apna data asani sa manipulate krsakta ha or used krsakta
ha
multidimensionarray means aik ziada array


In [3]:
#ab br numpy likna ka bjae mna isko np sa initialize kr dya ab brbr numpy nhi
#likha ga just np likha ga  
import numpy as np
#now we generate random number we write  np.random.randn likha ga numpy ma to wo
#mujha random number generate krda ga
#ab mna jo (2,3) likha ha is ma 2 ka matlab ya ha apko do array chaya or ,3 
#ka matlab ya ha ka apko hr array ka  ander 3 random number chya ha 
data = np.random.randn(2,3)
print(data)

[[-0.24256148  0.89209135  0.79283959]
 [ 0.61369636  1.33822495 -0.61646556]]


In [5]:
import numpy as np

data = np.random.randn(2,3)
print(data,'\n')
print(data+data)
#ab ma charha hon data ka ander jo cheez generate hue ha wo dobra isi kaander 
#add hojaga 

[[ 0.28499826 -0.52386444  0.44872098]
 [-1.7642614   0.92611078  0.35784252]] 

[[ 0.56999651 -1.04772887  0.89744195]
 [-3.52852279  1.85222156  0.71568503]]


In [7]:
import numpy as np

data = np.random.randn(2,3)
print(data,'\n')
print(data+data,'\n')
print(data * 10)#data ka ander jitna bhi number ha inko multiply krdo 10 sa



[[-1.21872272  1.43879783  1.45366364]
 [-0.3195293  -0.20528695  2.01190914]] 

[[-2.43744545  2.87759567  2.90732728]
 [-0.63905859 -0.4105739   4.02381828]] 

[[-12.18722724  14.38797833  14.53663639]
 [ -3.19529296  -2.05286949  20.11909141]]


In [9]:
import numpy as np

data = np.random.randn(2,3)
print(data,'\n')
print(data+data,'\n')
print(data * 10,'\n')
print(data.shape)#data.shape mujha ya btata ha ap ka ps kitni arrays ha or is
#ma kitna number ha 

[[ 1.42926102  1.22490422  1.33070662]
 [ 0.5801076   0.16472292 -0.91567539]] 

[[ 2.85852203  2.44980845  2.66141324]
 [ 1.16021521  0.32944583 -1.83135078]] 

[[14.29261017 12.24904223 13.30706619]
 [ 5.80107603  1.64722915 -9.15675392]] 

(2, 3)


In [10]:
import numpy as np

data = np.random.randn(2,3)
print(data,'\n')
print(data+data,'\n')
print(data * 10,'\n')
print(data.shape,'\n')
print(data.dtype,'\n')#dtype hamra ps data type btata ha ka hamara data kis type
#ka ha 

[[ 0.83139333 -0.35149301 -1.33827972]
 [ 0.5932859  -1.8717502   0.15206335]] 

[[ 1.66278666 -0.70298602 -2.67655944]
 [ 1.1865718  -3.7435004   0.30412669]] 

[[  8.3139333   -3.51493012 -13.3827972 ]
 [  5.93285898 -18.71750199   1.52063347]] 

(2, 3) 

float64 



In [12]:
import numpy as np

data = np.random.randn(2,3)
print(data,'\n')
print(data+data,'\n')
print(data * 10,'\n')
print(data.shape,'\n')
print(data.dtype,'\n')
print(data.ndim,'\n')#n means number or dim means dimension ka hara ps
# kitni array generate hue ha


[[ 0.92028275  0.64990402 -0.78616825]
 [-0.19304018  0.62941743 -2.95983643]] 

[[ 1.8405655   1.29980804 -1.5723365 ]
 [-0.38608036  1.25883487 -5.91967287]] 

[[  9.20282748   6.49904022  -7.86168249]
 [ -1.93040178   6.29417435 -29.59836434]] 

(2, 3) 

float64 

2 



In [13]:
#Numpy apko functionality deta ha ap zero ki array bhi generate kr sakta ha
print(np.zeros(10))#humna aik jga numpy ko initialize krdiya ab hum hr jga 
#np ka zarya np ko used krsakta ha
#10 represent no of zero



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')#ab humna 3 arry bnae or is ma 6 zeros dala

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [16]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,6)),'\n')#ab yha isna 2 array generate kiya iska ander
#3 array or banay or is ma 6 zero dal diya 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 



In [19]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,6)),'\n')
#isi trh hamra numpy ma empty ka module ab is ko dektha wo kaisa used hota ha
print('it is empty example \n',np.empty((3,6)),'\n')
#ab yha empty or zero ma ya difference ha ka empty apko hr 0 daga or kabhi apko 
#garbage value daga jiska matlab koi bhi value 
#to zaroori nhi ha is lya agr apko zero ki need ha to ap np.zeros print kra

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

it is empty example 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [22]:
#ab yha arra bnae ha ab is normal arry ko numpy ki arry bnae ga hum
arr = np.array([1,2,3,4,5,6])#ab yha ma jo bhi value doga wo numpy 
#ki array bn jaage
#ab ma chata hon ya value jo int ma ha wo float ma convert hojaa iskaly
#hum used kra ga astype() or bracket ka ander jis ma convert krna ha wo 
#likh da suppose float ka np.float
print(arr.astype(np.float64))
#means isna aik integer array ko float ma convert krdiya ha

[1. 2. 3. 4. 5. 6.]


In [21]:
arr = np.array([1,2,3,4,5,6])
print(arr.astype(np.float64))


[1. 2. 3. 4. 5. 6.]


In [23]:
arr = np.array([4,2,3,6,9],dtype='int64')#hum array bnata waqt iski data type bhi initialize
#kr sakta ha
print(arr *2)

[ 8  4  6 12 18]


In [31]:
arr = np.array([4,2,3,6,9],dtype='int64')
print(arr,'\n')
print(arr *2,'\n')

[4 2 3 6 9] 

[ 8  4  6 12 18] 



In [32]:
arr = np.array([4,2,3,6,9],dtype='int64')
print(arr,'\n')
print(arr *2,'\n')
print(arr * arr,'\n')

[4 2 3 6 9] 

[ 8  4  6 12 18] 

[16  4  9 36 81] 



In [46]:
arr = np.array([4,2,3,6,9],dtype='int64')
print(arr,'\n')
print(arr *2,'\n')
print(arr * arr,'\n')
print(2 * arr,'\n')
print(arr ** 2,'\n')#**(for power)
print(np.sqrt(arr),'\n')# for square root
print(np.exp(arr),'\n')#for exponent
print(np.mean(arr),'\n')#Statistics operation (mean,median and mode)
print(np.sum(arr),'\n')#sum
print(np.cumsum(arr),'\n')#cumsum yani 4 ko 2 ma add kiya phir iska baad indono 
#ka result ko next value ma add kiya like 3 ma kiya and so on
print(np.sort(arr),'\n')#sort(arrange)
# now we do boolean operation
#> < 
#mujha check krna arry1 ki value arr2 ki value sa bari ha ya nhi
arr2 =np.array([0,1,3,5,4])
print(arr > arr2)
print(arr < arr2)

[4 2 3 6 9] 

[ 8  4  6 12 18] 

[16  4  9 36 81] 

[ 8  4  6 12 18] 

[16  4  9 36 81] 

[2.         1.41421356 1.73205081 2.44948974 3.        ] 

[5.45981500e+01 7.38905610e+00 2.00855369e+01 4.03428793e+02
 8.10308393e+03] 

4.8 

24 

[ 4  6  9 15 24] 

[2 3 4 6 9] 

[ True  True False  True  True]
[False False False False False]


In [50]:
#ab humko range ka function used krta python ma but numpy ma hum arange used
#krta ha
arr = np.arange(10)#ab mna arange 0 to taq ki value ko arrange bhi kya
#or generate bhi
print(arr)
 
arr2=arr[5:8]
print(arr2)
arr[:3]=0 #jin element ko slicing ki in tamam ko zero sa replace krdega ga 
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [25]:
namesArr = np.array(["ali","raza","fahad","hussain","ali"])
#jitna  element first list ma hoga itna array generate kra 
# second arr ma  means 5 (5,3)
numArr = np.random.randn(5,3)
print(numArr ,'\n')
print(namesArr ,'\n')
print(namesArr == "ali",'\n')
print(numArr[namesArr == "ali"],'\n')#numArr ka ander check kro kya cheez ka ali apko
#apko kha kha mil rha ha jha  jha ap ko ali mila is arr ma sa wo wala arr ko
#(value) ko uthao or print krdo to isna first wali arry or last lakr print kr di
#jha isko ali mila 
print(numArr[~(namesArr == "ali")],'\n')#~ not ka operation
#ab 3 jga ali nhi tha islya inteen jga print kiya
print(np.unique(namesArr),'\n')#hr element ko  print krddga jo repeat 
#horha  ho aik dafa print krda  ga or sath ma sorting bhi krda ga(A,F,H,R)


[[ 1.9131925   0.37794082 -0.77263504]
 [-1.21652018  0.86442433 -1.15933801]
 [ 0.79958309  1.84871323 -0.6083352 ]
 [-0.1187217  -0.8915983   0.21199454]
 [ 1.13399168 -0.34388823 -0.9881022 ]] 

['ali' 'raza' 'fahad' 'hussain' 'ali'] 

[ True False False False  True] 

[[ 1.9131925   0.37794082 -0.77263504]
 [ 1.13399168 -0.34388823 -0.9881022 ]] 

[[-1.21652018  0.86442433 -1.15933801]
 [ 0.79958309  1.84871323 -0.6083352 ]
 [-0.1187217  -0.8915983   0.21199454]] 

['ali' 'fahad' 'hussain' 'raza'] 



In [10]:
import numpy as np
arr1 =np.random.randn(4)
print(arr1,'\n')
arr2 =np.random.randn(4)
print(arr2,'\n')
print(np.maximum(arr1,arr2),'\n')
print(np.minimum(arr1,arr2),'\n')

[ 2.35067012 -0.07733842  0.21559631  0.48907755] 

[-0.50620323 -2.23560299 -0.87194993  1.64280063] 

[ 2.35067012 -0.07733842  0.21559631  1.64280063] 

[-0.50620323 -2.23560299 -0.87194993  0.48907755] 

